### ISSUE TITLE
Add link to Sygma Explorer after deposit is created

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-widget#53] opened 2024-01-12 17:11 UTC
## Implementation details

- Once deposit is submited add link to Explorer UI to track status of the transaction

## Acceptance Criteria

- once deposited, link to the Explorer UI should lead to the detail view

**Comment by mpetrunic** [comment] 2024-02-06 13:58
duplicate of #22

**Closed by mpetrunic** 2024-02-06 13:58 UTC
Labels: Priority: P2
